server:
  port: 10001

spring:
  application:
    name: demo-auth
  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 自动路由
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
  instance:
    lease-renewal-interval-in-seconds: 10 # 租约更新时间（心跳上报间隔时间）
    lease-expiration-duration-in-seconds: 20 # 租约到期持续时间（心跳上报最大容忍时间）


# actuator 配置
management:
  security:
    enabled: false # 关闭安全检查 （仅供测试）
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口
  endpoint:
    health:
      show-details: always