server:
  port: 30000
management:
  server:
    port: 30001

spring:
  application:
    name: demo-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka # 注册中心（集群情况下，可多配置）
turbine:
  aggregator:
    cluster-config: default
  app-config: demo-client1 # 需要监控都服务
  cluster-name-expression: '"default"' # 默认集群
  combine-host-port: true # 根据host+port聚合服务，默认是只使用host
  instanceUrlSuffix:
    default: actuator/hystrix.stream

