# http://localhost:50000/{application}/{profile}
# http://localhost:50000/{application}/{profile}/{label}
# http://localhost:50000/{application}-{profile}.{suffix}
# http://localhost:50000/{label}/{application}-{profile}.{suffix}
server:
  port: 50000

spring:
  application:
    name: demo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gushizone/demo-spring-cloud-config.git
          force-pull: true # 强制拉取配置文件
          search-paths: '{application}' # 将配置文件放到接入方服务名称对应文件夹下面
#          username:
#          password:
        # 覆盖属性
#        overrides:
#          config:
#            source: config


#  可选：借助eureka实现高可用
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka # 注册中心（集群情况下，可多配置）
  instance:
    lease-renewal-interval-in-seconds: 10 # 租约更新时间（心跳上报间隔时间）
    lease-expiration-duration-in-seconds: 20 # 租约到期持续时间（心跳上报最大容忍时间）